name: server deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying to development server
    steps:
      - name: setup ssh and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_SSH_KEY}}" &> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{secrets.EC2_KNOWN_HOSTS}}" &> ~/.ssh/known_hosts

      - name: deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{secrets.EC2_DEV_IP}} << 'EOF'
            cd LMS-BE && git pull
            npm install
            pm2 restart api-dev-server
          EOF
